eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA.SERVER.HOST:http://localhost:8761/eureka}


#Enable Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator

#Actuator configuration
info:
  app:
    name: Product Service
    description: Product Service
    version: 0.0.1