server:
  port: ${CUSTOM.SERVER.PORT:8088}

# Mongo Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27017/mitocode?authSource=admin}

mitocode:
  security:
    key: mitocode