server:
  port: ${CUSTOM.SERVER.PORT:9080}

# Spring Cloud Gateway Routes
spring:
  cloud:
    gateway:
      routes:


/api/product/financial 

        - id: product-service-route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=2

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2