server:
  port: ${CUSTOM.SERVER.PORT:9022}

# Mongo Configuration
spring:
  data:
    mongodb:
      uri: ${MONGODB.URL.CONNECTION:mongodb://mitocode:mitocode@localhost:27018/mitocode?authSource=admin}
      